### PR TITLE
Use name where licence number isn't present

### LINKED ISSUE #322: When Crew license # doesn't exist, Crew member page 'name' is "N/A"
**Describe the bug**

**To Reproduce**
1. Create a boarding record where there is a crew member with a name but no license
2. Login to the web interface, click "Boarding Records" -> Crew
3. Choose the crew member without a license
4. See that the name is "N/A"

**Expected behavior**
The name should properly appear

**Screenshots**
Here's an example of the "Boarding Records" -> Crew page:
Screen Shot 2020-10-16 at 10 19 51 AM

And when I click on "Stowaway" here's what I see:
Screen Shot 2020-10-16 at 10 19 59 AM

(instead of N/A it should say "Stowaway" at the top)

### PR DESCRIPTION
**Pull request by ayushjainrksh**
## Related Issue
Fixes #322 

## Approach
Check for `captain name` if `captain licence` isn't present to identify the crew is a captain and send the respective name to search for data.

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [ ] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)

### CODE REVIEW

File: src/components/crew/crew-view/crew-view.component.js [hunk 1]
```diff
@@ -51,12 +51,14 @@ class CrewViewPage extends Component {
 
   componentDidMount() {
     const filter = JSON.parse(this.props.match.params.filter);
-    const isCaptain =  filter["captain.license"] !== undefined;
-    let licenseNumber;
+    const isCaptain =  filter["captain.licence"] !== undefined || filter["captain.name"] !== undefined;
```
Comment (ayushjainrksh) [inline src/components/crew/crew-view/crew-view.component.js:54]: To identify if the crew is a captain when `licence number` is absent.

File: src/components/crew/crew-view/crew-view.component.js [hunk 2]
```diff
@@ -73,8 +75,8 @@ class CrewViewPage extends Component {
             notes: dataHelper.getNotes(licenseNumber),
             captainName: dataHelper.getCaptainName(licenseNumber),
             crewName: isCaptain ?
-              dataHelper.getCaptainName(licenseNumber):
-              dataHelper.getCrewName(licenseNumber),
+              dataHelper.getCaptainName(licenseNumber || captainName):
+              dataHelper.getCrewName(licenseNumber || crewName),
```
Comment (ayushjainrksh) [inline src/components/crew/crew-view/crew-view.component.js:79]: The `dataHelper` functions find data using name when licence number is absent.

https://github.com/WildAid/o-fish-web/blob/14fbb743b9061e79ac4a48c8b9eb63a9194f66c6/src/components/partials/boarding-data.helper.js#L205-L213

File: src/components/crew/crew-view/crew-view.component.js (hunk 1 above)
Comment (Sheeri) [reply src/components/crew/crew-view/crew-view.component.js:54]: This is not working properly, and I wonder if it's because the field is captain.license (not captain.licence)?

**Review by Sheeri — CHANGES_REQUESTED** [review]
I couldn't get this to display information when there was a crew member with a name but no license. e.g. http://localhost:3000/#/crew/view/{%22crew.name%22:%22Stowaway%22} (where I had a crew member named 'Stowaway' with no license number.

File: src/components/crew/crew-view/crew-view.component.js (hunk 1 above)
Comment (ayushjainrksh) [reply src/components/crew/crew-view/crew-view.component.js:54]: Sorry for this. I'll make an amend.

File: src/components/partials/boarding-data.helper.js [hunk 3]
```diff
@@ -188,12 +188,12 @@ export default class BoardingDataHelper {
...
   }
 
-  getCrewName(license) {
+  getCrewName(item) {
     let name;
     this.boardings.forEach((boarding) => {
       if (boarding.crew && boarding.crew.length) {
         for (let crew of boarding.crew) {
-          if (crew.license === license) {
+          if (crew.license === item || crew.name === item) {
```
Comment (ayushjainrksh) [inline src/components/partials/boarding-data.helper.js:196]: Earlier I missed out the `crew name` function. This is fixed now.

**Comment by ayushjainrksh** [comment]
@Sheeri It should be working now.

**Review by Sheeri — APPROVED** [review]
This looks great! Thanks.

**Comment by Sheeri** [comment]
Congratulations! 🎉 🙌 🎆 ㊗️ 

This PR is great and has been merged into the code. Thanks so much for contributing! If you'd like, you can request to work on another issue. We really appreciate your effort!

To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.
