### PR TITLE
get correct link for PreviewItem and some cleanup of VIEW_BOARDING_PAGE

### LINKED ISSUE #353: Search results for a vessel should go directly to that vessel
**Describe the bug**
Search results for a vessel currently get redirected to the "Vessels" page for the search item, not the actual record clicked.

**To Reproduce**
1. Log in
2. Make sure "All" is set in the search bar:
Screen Shot 2020-10-28 at 4 10 55 PM

3. Put in a search term that will match at least one vessel
4. Click on the vessel that shows up in the results, e.g. here I searched for "boat" and will click on "My Boat":
Screen Shot 2020-10-28 at 4 12 01 PM

5. The page that shows up is the vessel search page, not the individual boarding record. e.g. this is the page that shows up (it has a url of /#/vessels/null):
Screen Shot 2020-10-28 at 4 12 29 PM

When it should be this (with a URL of https://wildaidsandbox-mxgfy.mongodbstitch.com/#/vessels/view/{"vessel.permitNumber":"12345","vessel.name":"My Boat"}):

Screen Shot 2020-10-28 at 4 13 30 PM

**Expected behavior**
Instead of redirecting to the **vessels** page, the search should redirect to the appropriate **vessels/view** page.

### PR DESCRIPTION
**Pull request by lenmorld**
## Related Issue

Fixes #353

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [x] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)

* **Optional: Add any explanations here** 

- removed the incorrect link with null filters in PreviewItem
- used get*ViewPage methods from get-data to get link for Vessels, Crews, and Boardings
- make sure that PreviewItem is not rendered when item not there yet
- added a reusable method getBoardingViewPage to get-data

Additional:
- cleanup all usage of VIEW_BOARDING_PAGE into reusable goBoardingViewPage

* **Optional: Add any relevant screenshots here**

### CODE REVIEW

File: src/components/autofill/preview-item/preview-item.component.js [hunk 1]
```diff
@@ -2,36 +2,24 @@ import React, { memo } from "react";
...
-    case "BOARDINGS": searchResultsLink = BOARDINGS_PAGE.replace(":filter", null)
-    break;
-    case "VESSELS": searchResultsLink = VESSELS_PAGE.replace(":filter", null)
-    break;
-    case "CREW MEMBERS": searchResultsLink = CREW_PAGE.replace(":filter", null)
-    break;
-    default: searchResultsLink="#"
-    break;
-  }
-
```
Comment (lenmorld) [inline src/components/autofill/preview-item/preview-item.component.js:34]: removed the incorrect link with null filters

File: src/components/autofill/preview-item/preview-item.component.js [hunk 2]
```diff
@@ -2,36 +2,24 @@ import React, { memo } from "react";
...
 
 import TextViewer from "../../partials/text-viewer/text-viewer";
 
 import "../autofill.css";
-import { Link } from "react-router-dom";
-import { BOARDINGS_PAGE, CREW_PAGE, VESSELS_PAGE } from "../../../root/root.constants";
 
 const PreviewItem = ({
   item,
+  itemInfoLink,
```
Comment (lenmorld) [inline src/components/autofill/preview-item/preview-item.component.js:15]: used `itemInfoLink` prop consistent with search-results page

File: src/components/autofill/autofill.component.js [hunk 3]
```diff
@@ -7,38 +7,53 @@ import PreviewItem from "./preview-item/preview-item.component";
...
+            itemName={t("SEARCH.CREW_MEMBERS").toUpperCase()}
+            icon="crew"
+            previewName="name"
+            subText={t("NAVIGATION.VESSELS")}
+            searchWords={searchWords}
+            itemInfoLink={getCrewViewPageWithFilter(firstCrew)}
+          />
+        }
+        {
+          firstBoarding && <PreviewItem
```
Comment (lenmorld) [inline src/components/autofill/autofill.component.js:47]: made sure that the Previewitem is only rendered if item already exists

File: src/components/autofill/autofill.component.js [hunk 4]
```diff
@@ -7,38 +7,53 @@ import PreviewItem from "./preview-item/preview-item.component";
 
 import { SEARCH_RESULTS_PAGE } from "./../../root/root.constants";
 
+import { getCrewViewPageWithFilter, getVesselViewPageWithFilter, getBoardingViewPage } from "../../helpers/get-data"
+
```
Comment (lenmorld) [inline src/components/autofill/autofill.component.js:11]: used the reusable methods to get path with link

File: src/components/boardings/boarding-edit/boarding-edit.component.js [hunk 5]
```diff
@@ -62,11 +60,9 @@ class BoardingEditPage extends Component {
     this.validateSchema();
     boardingService.updateBoarding(this.dataObject).then((result) => {
       if (this.state.isNew) {
-        history.push(VIEW_BOARDING_PAGE.replace(":id", result.insertedId));
+        goBoardingViewPage(result.insertedId);
       } else {
-        history.push(
-          VIEW_BOARDING_PAGE.replace(":id", this.state.dataObject._id)
-        );
+        goBoardingViewPage(this.state.dataObject._id);
```
Comment (lenmorld) [inline src/components/boardings/boarding-edit/boarding-edit.component.js:65]: reuse shared method in `getData`

File: src/components/boardings/boardings-table/boardings-table.component.js [hunk 6]
```diff
@@ -66,7 +64,7 @@ class BoardingsTable extends Component {
                 <tr
                   className="table-row row-body"
                   key={ind}
-                  onClick={() => goToPage(VIEW_BOARDING_PAGE, item._id)}
+                  onClick={() => goBoardingViewPage(item._id)}
```
Comment (lenmorld) [inline src/components/boardings/boardings-table/boardings-table.component.js:67]: reuse shared method in `getData`

File: src/components/partials/overview-pages/boardings-overview/boardings-overview.component.js [hunk 7]
```diff
@@ -43,7 +42,7 @@ const BoardingsOverview = ({ t, boardings, filter }) => (
                   key={ind}
                   className="table-row row-body"
                   onClick={() =>
-                    goToPage(VIEW_BOARDING_PAGE, boarding.id)
+                    goBoardingViewPage(boarding.id)
```
Comment (lenmorld) [inline src/components/partials/overview-pages/boardings-overview/boardings-overview.component.js:45]: reuse shared method in `getData`

File: src/components/boardings/boarding-edit/boarding-edit.component.js (hunk 5 above)
Comment (lenmorld) [reply src/components/boardings/boarding-edit/boarding-edit.component.js:65]: applies to all the other changes to `boardings` pages
that manually used `VIEW_BOARDING_PAGE` before

File: src/helpers/get-data.js [hunk 8]
```diff
@@ -284,3 +284,13 @@ export const getCrewViewPageWithFilter = (crew) => {
...
+
+export const getBoardingViewPage = (boardingId) => {
+  let path = VIEW_BOARDING_PAGE;
+  path = path.replace(":id", boardingId);
+  return path;
+}
+
+export const goBoardingViewPage = (boardingId) => {
+  history.push(getBoardingViewPage(boardingId));
+}
```
Comment (lenmorld) [inline src/helpers/get-data.js:296]: added reusable methods to manipulate and use `VIEW_BOARDING_PAGE`

**Review by Sheeri — APPROVED** [review]
This is great - you really did a good job making sure all the code reuse and optimizations were in the correct places. Thanks!

**Comment by Sheeri** [comment]
Congratulations! 🎉 🙌 🎆 ㊗️ 

This PR is great and has been merged into the code. Thanks so much for contributing! If you'd like, you can request to work on another issue. We really appreciate your effort!

To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.
